[versions]
android-gradle-plugin = "7.4.0-alpha05"
spotless = "6.7.2"

[libraries]
gradle-plugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
gradle-plugin-spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }

[bundles]
dsl = [
    "gradle-plugin-android",
    "gradle-plugin-spotless",
]
